//! `issen-carvers` — internal aggregator umbrella (NOT a carver itself).
//!
//! Force-links every disk carver crate listed in this crate's own `Cargo.toml`
//! `[dependencies]`, so each carver's `inventory::submit! { CarverRegistration }`
//! survives dead-code elimination in any artifact that links `issen_carvers`. The
//! anchors are generated by `build.rs` from the manifest — there are zero
//! hand-written `extern crate` lines. Adding a carver is one dependency line in
//! `Cargo.toml`.
//!
//! `issen_cli`'s `lib.rs` carries a real `extern crate issen_carvers as _;` root
//! anchor so this crate (and therefore the whole generated anchor set) is itself
//! pulled into the link, exactly as `issen_parsers` anchors the parser fleet.
#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]

include!(concat!(env!("OUT_DIR"), "/anchors.rs"));

#[cfg(test)]
mod carver_registration {
    //! Unit 1 (fleet ADR 0001 §1/§4): force-linking the disk carver crates must
    //! make their `inventory::submit!` registrations reachable via
    //! `forensic_carve::registered_carvers()` from within an issen binary. If a
    //! producer crate is dropped from `[dependencies]`, its carver is dead-code-
    //! eliminated and silently never runs — this test is the backstop.

    #[test]
    fn disk_carvers_are_registered() {
        let formats: Vec<&str> = forensic_carve::registered_carvers()
            .iter()
            .map(|c| c.format())
            .collect();
        for expected in ["sqlite", "evtx-chunk", "registry-hive"] {
            assert!(
                formats.contains(&expected),
                "carver format {expected:?} is not registered — force-link its \
                 producer crate in issen-carvers/Cargo.toml [dependencies] \
                 (registered: {formats:?})"
            );
        }
    }
}

#[cfg(test)]
mod drift_gate {
    //! Anchor-completeness gate: every direct normal dependency declared in this
    //! crate's own `Cargo.toml` MUST appear as a real `extern crate <dep> as _;`
    //! in the generated `anchors.rs`. If build.rs ever silently drops a dep (or a
    //! dep is added without regenerating), this fails — a dropped anchor means the
    //! carver's `inventory::submit!` is dead-code-eliminated and it never runs.

    const ANCHORS_RS: &str = include_str!(concat!(env!("OUT_DIR"), "/anchors.rs"));
    const MANIFEST: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/Cargo.toml"));

    /// Direct normal deps declared under `[dependencies]` in this crate's manifest.
    fn manifest_deps() -> Vec<String> {
        let manifest: toml::Value = MANIFEST.parse().expect("aggregator Cargo.toml parses");
        manifest
            .get("dependencies")
            .and_then(toml::Value::as_table)
            .map(|t| t.keys().cloned().collect())
            .unwrap_or_default()
    }

    #[test]
    fn every_manifest_dep_is_anchored() {
        let missing: Vec<String> = manifest_deps()
            .into_iter()
            .filter(|dep| {
                let line = format!("extern crate {} as _;", dep.replace('-', "_"));
                !ANCHORS_RS.contains(&line)
            })
            .collect();
        assert!(
            missing.is_empty(),
            "these manifest deps are NOT anchored in the generated anchors.rs — \
             their inventory registrations will be dead-code-eliminated and the \
             carver will silently never run: {missing:?}"
        );
    }
}
